export const ApiEndpoints = {
  auth: {
    base: "/auth",
    login: "/adminLogin",
    register: "/register",
    update: "/update",
  },
  children: {
    base: "/children",
    getAll: "/get",
    getById: "/getById",
    create: "/create",
    update: "/update",
    delete: "/delete",
  },
  categories: {
    base: "/category",
    getAll: "/get",
    getById: "/getById",
    create: "/create",
    update: "/update",
    delete: "/delete",
    updateOrder: "/order",
  },
  subCategory: {
    base: "/subCategory",
    getAll: "/get",
    getById: "/getById",
    create: "/create",
    update: "/update",
    delete: "/delete",
  },
  products: {
    base: "/product",
    getAll: "/getAdminProduct",
    getById: "/getProductById/",
    create: "/createProduct",
    update: "/updateProduct/",
    delete: "/deleteProduct",
  },
  pages: {
    base: "/pages",
    getAll: "/getAll",
    getById: "/getById",
    create: "/create",
    update: "/update",
    delete: "/delete",
  },
  uploadImage: {
    base: "/image",
    upload: "/uploadImage",
  },
  content: {
    base: "/content",
    getAll: "/get",
    getById: "/getById",
    getBySlug: "/getBySlug",
    create: "/create",
    update: "/update",
    delete: "/delete",
    updateToggle: "/toggle",
    updateOrder: "/order",
  },
  users: {
    base: "/auth",
    getAll: "/getUsers",
    deleteUser: "/deleteUser",
    disableUser: "/disableUser",
    updateUserPassword: "/updateUserPassword",
    getUserById: "/getUserById"
  },
  blogs: {
    base: "/blogs",
    getAll: "/getAdmin",
    create: "/create",
    update: "/update",
    delete: "/delete",
    toggle: "/toggle",
  },
  home: {
    create: "/homePage/create",
  },
  orders: {
    base: "/order",
    getAll: "/list",
    cancelRecurring: "/cancel-subscription",
    getById: "/getbyid",
  },
};
