export const SignupConstants = {
  SIGN_UP_LOADING: 'SIGN_UP_LOADING',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
}
export const EmailVerifyConstants = {
  EMAIL_VERIFY_LOADING: 'EMAIL_VERIFY_LOADING',
  EMAIL_VERIFY_SUCCESS: 'EMAIL_VERIFY_SUCCESS',
  EMAIL_VERIFY_ERROR: 'EMAIL_VERIFY_ERROR',
}

export const UserDataConstants = {
  USER_DATA_LOADING: 'USER_DATA_LOADING',
  USER_DATA_SUCCESS: 'USER_DATA_SUCCESS',
  USER_DATA_ERROR: 'USER_DATA_ERROR',
}

export const SignInConstants = {
  SIGN_IN_LOADING: 'SIGN_IN_LOADING',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
}

export const DarkModeConstants = {
  DARK_MODE_LOADING: 'DARK_MODE_LOADING',
  DARK_MODE_SUCCESS: 'DARK_MODE_SUCCESS',
  DARK_MODE_ERROR: 'DARK_MODE_ERROR',
}
export const SetDrawerStateConstants = {
  DRAWER_OPEN_LOADING: 'DRAWER_OPEN_LOADING',
  DRAWER_OPEN_SUCCESS: 'DRAWER_OPEN_SUCCESS',
  DRAWER_OPEN_ERROR: 'DRAWER_OPEN_ERROR',
}
export const GetAllUsersConstants = {
  GET_USERS_LOADING: 'GET_USERS_LOADING',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
}
export const DeleteUserConstants = {
  DELETE_USER_LOADING: 'DELETE_USER_LOADING',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_ERROR: 'DELETE_USER_ERROR',
}

export const GetAllBarbersConstants = {
  GET_ALL_BARBERS_LOADING: 'GET_ALL_BARBERS_LOADING',
  GET_ALL_BARBERS_SUCCESS: 'GET_ALL_BARBERS_SUCCESS',
  GET_ALL_BARBERS_ERROR: 'GET_ALL_BARBERS_ERROR',
}

export const GetAllBookingConstants = {
  GET_ALL_BOOKINGS_LOADING: 'GET_ALL_BOOKINGS_LOADING',
  GET_ALL_BOOKINGS_SUCCESS: 'GET_ALL_BOOKINGS_SUCCESS',
  GET_ALL_BOOKINGS_ERROR: 'GET_ALL_BOOKINGS_ERROR',
}

export const GetAllServicesConstant = {
  GET_ALL_SERVICES_LOADING: 'GET_ALL_SERVICES_LOADING',
  GET_ALL_SERVICES_SUCCESS: 'GET_ALL_SERVICES_SUCCESS',
  GET_ALL_SERVICES_ERROR: 'GET_ALL_SERVICES_ERROR',
}

export const AddPackageDetailConstant = {
  ADD_PACKAGE_DETAIL_LOADING: 'ADD_PACKAGE_DETAIL_LOADING',
  ADD_PACKAGE_DETAIL_SUCCESS: 'ADD_PACKAGE_DETAIL_SUCCESS',
  ADD_PACKAGE_DETAIL_ERROR: 'ADD_PACKAGE_DETAIL_ERROR',
}
export const GetAllPacakagesConstant = {
  GET_ALL_PACKAGES_LOADING: 'GET_ALL_PACKAGES_LOADING',
  GET_ALL_PACKAGES_SUCCESS: 'GET_ALL_PACKAGES_SUCCESS',
  GET_ALL_PACKAGES_ERROR: 'GET_ALL_PACKAGES_ERROR',
}
export const GetAllPacakagesByTypeConstant = {
  GET_ALL_PACKAGES_BY_TYPE_LOADING: 'GET_ALL_PACKAGES_BY_TYPE_LOADING',
  GET_ALL_PACKAGES_BY_TYPE_SUCCESS: 'GET_ALL_PACKAGES_BY_TYPE_SUCCESS',
  GET_ALL_PACKAGES_BY_TYPE_ERROR: 'GET_ALL_PACKAGES_BY_TYPE_ERROR',
}
export const SelectServiceConstant = {
  SERVICE_SELECT_LOADING: 'SERVICE_SELECT_LOADING',
  SERVICE_SELECT_SUCCESS: 'SERVICE_SELECT_SUCCESS',
  SERVICE_SELECT_ERROR: 'SERVICE_SELECT_ERROR',
}
export const AddBarberDetailConstant = {
  ADD_BARBER_DETAIL_LOADING: 'ADD_BARBER_DETAIL_LOADING',
  ADD_BARBER_DETAIL_SUCCESS: 'ADD_BARBER_DETAIL_SUCCESS',
  ADD_BARBER_DETAIL_ERROR: 'ADD_BARBER_DETAIL_ERROR',
}
export const GetProfileContant = {
  GET_PROFILE_LOADING: 'GET_PROFILE_LOADING',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
}
